th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic1_densenetfft.png -model ./paper_test/densenet_fft_1.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic2_densenetfft.png -model ./paper_test/densenet_fft_2.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic3_densenetfft.png -model ./paper_test/densenet_fft_3.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic4_densenetfft.png -model ./paper_test/densenet_fft_4.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic5_densenetfft.png -model ./paper_test/densenet_fft_5.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic6_densenetfft.png -model ./paper_test/densenet_fft_6.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic7_densenetfft.png -model ./paper_test/densenet_fft_7.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic8_densenetfft.png -model ./paper_test/densenet_fft_8.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic9_densenetfft.png -model ./paper_test/densenet_fft_9.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic10_densenetfft.png -model ./paper_test/densenet_fft_10.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic11_densenetfft.png -model ./paper_test/densenet_fft_11.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic12_densenetfft.png -model ./paper_test/densenet_fft_12.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic13_densenetfft.png -model ./paper_test/densenet_fft_13.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic14_densenetfft.png -model ./paper_test/densenet_fft_14.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic15_densenetfft.png -model ./paper_test/densenet_fft_15.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic16_densenetfft.png -model ./paper_test/densenet_fft_16.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic17_densenetfft.png -model ./paper_test/densenet_fft_17.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic18_densenetfft.png -model ./paper_test/densenet_fft_18.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic19_densenetfft.png -model ./paper_test/densenet_fft_19.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic20_densenetfft.png -model ./paper_test/densenet_fft_20.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic21_densenetfft.png -model ./paper_test/densenet_fft_21.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic22_densenetfft.png -model ./paper_test/densenet_fft_22.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic23_densenetfft.png -model ./paper_test/densenet_fft_23.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic24_densenetfft.png -model ./paper_test/densenet_fft_24.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic25_densenetfft.png -model ./paper_test/densenet_fft_25.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic26_densenetfft.png -model ./paper_test/densenet_fft_26.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic27_densenetfft.png -model ./paper_test/densenet_fft_27.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic28_densenetfft.png -model ./paper_test/densenet_fft_28.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic29_densenetfft.png -model ./paper_test/densenet_fft_29.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic30_densenetfft.png -model ./paper_test/densenet_fft_30.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic31_densenetfft.png -model ./paper_test/densenet_fft_31.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic32_densenetfft.png -model ./paper_test/densenet_fft_32.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic33_densenetfft.png -model ./paper_test/densenet_fft_33.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic34_densenetfft.png -model ./paper_test/densenet_fft_34.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic35_densenetfft.png -model ./paper_test/densenet_fft_35.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic36_densenetfft.png -model ./paper_test/densenet_fft_36.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic37_densenetfft.png -model ./paper_test/densenet_fft_37.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic38_densenetfft.png -model ./paper_test/densenet_fft_38.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic39_densenetfft.png -model ./paper_test/densenet_fft_39.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic40_densenetfft.png -model ./paper_test/densenet_fft_40.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic41_densenetfft.png -model ./paper_test/densenet_fft_41.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic42_densenetfft.png -model ./paper_test/densenet_fft_42.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic43_densenetfft.png -model ./paper_test/densenet_fft_43.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic44_densenetfft.png -model ./paper_test/densenet_fft_44.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic45_densenetfft.png -model ./paper_test/densenet_fft_45.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic46_densenetfft.png -model ./paper_test/densenet_fft_46.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic47_densenetfft.png -model ./paper_test/densenet_fft_47.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic48_densenetfft.png -model ./paper_test/densenet_fft_48.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic49_densenetfft.png -model ./paper_test/densenet_fft_49.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic50_densenetfft.png -model ./paper_test/densenet_fft_50.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic51_densenetfft.png -model ./paper_test/densenet_fft_51.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic52_densenetfft.png -model ./paper_test/densenet_fft_52.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic53_densenetfft.png -model ./paper_test/densenet_fft_53.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic54_densenetfft.png -model ./paper_test/densenet_fft_54.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic55_densenetfft.png -model ./paper_test/densenet_fft_55.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic56_densenetfft.png -model ./paper_test/densenet_fft_56.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic57_densenetfft.png -model ./paper_test/densenet_fft_57.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic58_densenetfft.png -model ./paper_test/densenet_fft_58.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic59_densenetfft.png -model ./paper_test/densenet_fft_59.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic60_densenetfft.png -model ./paper_test/densenet_fft_60.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic61_densenetfft.png -model ./paper_test/densenet_fft_61.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic62_densenetfft.png -model ./paper_test/densenet_fft_62.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic63_densenetfft.png -model ./paper_test/densenet_fft_63.t7


th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic1_densenet_.png -model ./checkpoint_densenet_final/test4_1.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic2_densenet_.png -model ./checkpoint_densenet_final/test4_2.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic3_densenet_.png -model ./checkpoint_densenet_final/test4_3.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic4_densenet_.png -model ./checkpoint_densenet_final/test4_4.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic5_densenet_.png -model ./checkpoint_densenet_final/test4_5.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic6_densenet_.png -model ./checkpoint_densenet_final/test4_6.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic7_densenet_.png -model ./checkpoint_densenet_final/test4_7.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic8_densenet_.png -model ./checkpoint_densenet_final/test4_8.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic9_densenet_.png -model ./checkpoint_densenet_final/test4_9.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic10_densenet_.png -model ./checkpoint_densenet_final/test4_10.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic11_densenet_.png -model ./checkpoint_densenet_final/test4_11.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic12_densenet_.png -model ./checkpoint_densenet_final/test4_12.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic13_densenet_.png -model ./checkpoint_densenet_final/test4_13.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic14_densenet_.png -model ./checkpoint_densenet_final/test4_14.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic15_densenet_.png -model ./checkpoint_densenet_final/test4_15.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic16_densenet_.png -model ./checkpoint_densenet_final/test4_16.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic17_densenet_.png -model ./checkpoint_densenet_final/test4_17.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic18_densenet_.png -model ./checkpoint_densenet_final/test4_18.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic19_densenet_.png -model ./checkpoint_densenet_final/test4_19.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic20_densenet_.png -model ./checkpoint_densenet_final/test4_20.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic21_densenet_.png -model ./checkpoint_densenet_final/test4_21.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic22_densenet_.png -model ./checkpoint_densenet_final/test4_22.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic23_densenet_.png -model ./checkpoint_densenet_final/test4_23.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic24_densenet_.png -model ./checkpoint_densenet_final/test4_24.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic25_densenet_.png -model ./checkpoint_densenet_final/test4_25.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic26_densenet_.png -model ./checkpoint_densenet_final/test4_26.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic27_densenet_.png -model ./checkpoint_densenet_final/test4_27.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic28_densenet_.png -model ./checkpoint_densenet_final/test4_28.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic29_densenet_.png -model ./checkpoint_densenet_final/test4_29.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic30_densenet_.png -model ./checkpoint_densenet_final/test4_30.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic31_densenet_.png -model ./checkpoint_densenet_final/test4_31.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic32_densenet_.png -model ./checkpoint_densenet_final/test4_32.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic33_densenet_.png -model ./checkpoint_densenet_final/test4_33.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic34_densenet_.png -model ./checkpoint_densenet_final/test4_34.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic35_densenet_.png -model ./checkpoint_densenet_final/test4_35.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic36_densenet_.png -model ./checkpoint_densenet_final/test4_36.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic37_densenet_.png -model ./checkpoint_densenet_final/test4_37.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic38_densenet_.png -model ./checkpoint_densenet_final/test4_38.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic39_densenet_.png -model ./checkpoint_densenet_final/test4_39.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic40_densenet_.png -model ./checkpoint_densenet_final/test4_40.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic41_densenet_.png -model ./checkpoint_densenet_final/test4_41.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic42_densenet_.png -model ./checkpoint_densenet_final/test4_42.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic43_densenet_.png -model ./checkpoint_densenet_final/test4_43.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic44_densenet_.png -model ./checkpoint_densenet_final/test4_44.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic45_densenet_.png -model ./checkpoint_densenet_final/test4_45.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic46_densenet_.png -model ./checkpoint_densenet_final/test4_46.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic47_densenet_.png -model ./checkpoint_densenet_final/test4_47.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic48_densenet_.png -model ./checkpoint_densenet_final/test4_48.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic49_densenet_.png -model ./checkpoint_densenet_final/test4_49.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic50_densenet_.png -model ./checkpoint_densenet_final/test4_50.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic51_densenet_.png -model ./checkpoint_densenet_final/test4_51.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic52_densenet_.png -model ./checkpoint_densenet_final/test4_52.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic53_densenet_.png -model ./checkpoint_densenet_final/test4_53.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic54_densenet_.png -model ./checkpoint_densenet_final/test4_54.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic55_densenet_.png -model ./checkpoint_densenet_final/test4_55.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic56_densenet_.png -model ./checkpoint_densenet_final/test4_56.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic57_densenet_.png -model ./checkpoint_densenet_final/test4_57.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic58_densenet_.png -model ./checkpoint_densenet_final/test4_58.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic59_densenet_.png -model ./checkpoint_densenet_final/test4_59.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic60_densenet_.png -model ./checkpoint_densenet_final/test4_60.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic61_densenet_.png -model ./checkpoint_densenet_final/test4_61.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic62_densenet_.png -model ./checkpoint_densenet_final/test4_62.t7
th test_origin.lua  -img /mnt/lvm/xiaojie/SelfExSR/data/Set14/image_SRF_4/img_005_SRF_4_LR.png -output ./paper_test_img/comic63_densenet_.png -model ./checkpoint_densenet_final/test4_63.t7
